---
title: "Building Data Products for Precision Medicine: Insights from Industry"
author: Nick Giangreco, PhD
format: 
  revealjs:
    incremental: true
    mermaid:
      theme: default
    css: styles.css
mermaid-format: svg
---

# Who am I?


```{mermaid}

flowchart LR
  HS(High School)-->College(Biochemistry)
  College-->Postbac(NIH)
  Postbac-->PhD(Columbia University)
  PhD-->Job(Regeneron Parmaceuticals)
  
```

# Where have I been?
```{mermaid}

flowchart LR
  A(Buffalo)-->B(Rochester)
  B-->C(Bethesda)
  C-->D(NYC)
  D-->A
  
```

# What's my background?

- Biology background
- Self-taught programmer
- Engineer for Precision Medicine

# Prelude
- My recovery from a brain injury taught me resilience 
- My resilience helped me excel in graduate school
- Be constructively critical of yourself - but know that you personally are amazing 

# What are we talking about today?
- Doing data science at a company
- Lessons from my graduate experience
- How to get the most out of being a student  
- Why you should harness AI as a tool

# What to take away
- Data science = **impact through clarity**  
- PhD/graduate school = **training for resilience**  
- AI = **Boost your productivity**  

# Doing Data Science at a Company
- At a company, you have deliverables, priorities, limited resources, and timelines
- Communicate the impact of your work - get used to making slides for stakeholders
- Ensure your data science/analytics is interpretable!
- Success = code + communication + collaboration  

# Lessons from a graduate student
- Do internships
- Take advantage of being a student
   - Network!
   - Learn as much as you can!
   - Experience matters
- Invest in your career
   - Go to conferences
   - Identify your domain
   - Learn what energizes you  

# Companies WANT you to leverage AI
- Use it to draft, code, summarize, ideate  
- Think of LLMs as assistants for increasing your productivity
- You are always needed to evaluate outputs
- Only use it when you know what you want

# Closing
- Student years: practice resilience, curiosity, communication, and NETWORKING!
- Industry: focus on communication and impact
- Final message: use your student time to build skills + mindset for impact
